Mark some tests as periodic and don't run them during regular e2e tests
openshift/cluster-api-actuator-pkg pull request #256
Opened 2022-11-14 14:15 UTC by Fedosin

Our test suite takes a long time to run and has a mixture of different types of tests. We don't really need to run some of these tests on every presubmit, but to keep checking them, could run them as periodics instead.

For example, the test that configures a cluster wide proxy, takes roughly 20-25 minutes to complete on AWS, every time we run a test job. This test has a significant cost associated with it, yet isn't that important to run so frequently.

Instead of running this on every job, we could run it as a periodic, eg every 72 hours, and from there set up an alert to notify us when the pass rate drops.

2022-11-14 15:00 UTC, JoelSpeed commented
For each test that you've marked as a periodic, can you please explain why you think this warrants being a periodic rather than running on presubmit?

I would like to be very deliberate about the tests that we mark as periodic, they should have good reasons behind them.

For example, it may be useful to make a test plan similar to the one for the CPMS which explains why each of these tests should be periodic and the behavioural subsets we cover in presubmits

2022-11-15 10:55 UTC, JoelSpeed commented
/retest

2022-11-15 15:57 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-16 12:54 UTC, JoelSpeed commented
/approve
/lgtm
/retest-required

2022-11-16 17:34 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-17 09:39 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-17 14:49 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-17 21:59 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-18 10:28 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-18 11:04 UTC, lobziik commented
Is this still actual after https://github.com/openshift/cluster-api-actuator-pkg/pull/258 was merged?

There I marked proxy test as periodic: https://github.com/openshift/cluster-api-actuator-pkg/pull/258/files#diff-ddf400001089ed146e8291e2e81b9fa305e9e371d81a389561ee6c61a11b8a5bR229

/hold

2022-11-18 11:34 UTC, lobziik requested changes
Think we don't need to explicitly exclude spot-tests

2022-11-18 11:34 UTC, lobziik commented on Makefile
> +	hack/ci-integration.sh $(GINKGO_ARGS) --label-filter='periodic && !spot-instances' -p
think `--label-filter='periodic'` should be enough

2022-11-18 11:37 UTC, lobziik commented
/lgtm

2022-11-18 15:40 UTC, Fedosin commented
/retest

2022-11-20 17:35 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-20 22:46 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-21 08:57 UTC, Fedosin commented
/test e2e-azure-operator

2022-11-21 10:25 UTC, JoelSpeed commented
/override ci/prow/e2e-azure-operator

The autoscaler test that's failing is unrelated to this change. I can see the proxy test is still being skipped and the new make target looks good to me, don't think we need this to pass

2022-11-21 10:29 UTC, merged